.gitignore
CMakeLists.txt
README.md
SCsub
src/bootstrap.cpp
src/gd_kotlin.cpp
src/java_instance_wrapper.cpp
src/java_instance_wrapper.h
src/jni/jvm.cpp
src/jni/jvm.h
src/jni/types.cpp
src/jni/types.h
src/kotlin_instance.cpp
src/kotlin_instance.h
src/kotlin_language.h
src/kotlin_script.cpp
src/kt_class.cpp
src/kt_class.h
src/kt_object.cpp
src/kt_object.h
src/transfer_context.cpp

Create new KotlinInstance from KotlinScript::instance_create, KotlinInstance constructor call create_instance of KtClass, which has to be implemented

create kotlin instance from KtScript

---

CMakeLists.txt
SCsub
src/gd_kotlin.cpp
src/gd_kotlin.h
src/java_instance_wrapper.h
src/jni/env.h
src/jni/jvm.cpp
src/jni/types.cpp
src/jni/types.h
src/jni/wrapper.h
src/kotlin_language.cpp
src/kt_class.h
src/kt_object.h
src/kt_variant.cpp
src/kt_variant.h

This needs to be tested.
I got it compiling on linux with those changes (still does not compile on windows)
Forward declarations were causing troubles, and protobuf was not linking.

Fix compilation incomplete type compilation error due to forward declare

---

CMakeLists.txt
kt/godot-runtime/src/main/kotlin/godot/core/KtClass.kt
src/kotlin_script.cpp
src/kt_class.cpp
src/kt_class.h
src/kt_function.cpp
src/kt_function.h
src/kt_property.cpp
src/kt_property.h

This add registration of kotlin properties at engine start.

Add registration of KtClass properties

---

README.md

This updates the readme to correct the local development instructions

Update local development instructions

---

src/bootstrap.cpp
src/gd_kotlin.cpp
src/jni/env.cpp
src/jni/types.cpp
src/jni/types.h
src/jni/wrapper.h
src/kt_class.cpp
src/kt_function.cpp
src/kt_property.cpp
src/transfer_context.cpp

This adds helper function to create array and get rid of static_initializer and conversions.

optimization/ remove list conversions in jni

---

.README/jetbrains.svg
README.md

Only to make sure that you are ok with adding it and that my english is not too bad :P

Add jetbrains support to readme

---

.github/workflows/check-pr-engine-editor-debug-and-tests.yaml
.github/workflows/check-pr-engine-editor-release.yaml
.github/workflows/check-pr-engine-export-template-debug.yaml
.github/workflows/check-pr-engine-export-template-release.yaml
.github/workflows/check-pr-jvm-godot-library.yaml
.github/workflows/check-pr-jvm-gradle-plugin.yaml

This adds the folder `kt/**` to the checks for release builds.

Bugfix: Fix PR checks for editor release builds

---

harness/tests/src/main/kotlin/godot/tests/Invocation.kt
harness/tests/test/unit/test_nullability_and_lateinit.gd
kt/godot-runtime/src/main/kotlin/godot/core/Functions.kt
kt/godot-runtime/src/main/kotlin/godot/runtime/Registration.kt

We forgot to support nullables as function params and return types. This implements it together with some tests that test this.
Depends on: https://github.com/utopia-rise/godot-kotlin-entry-generator/pull/18

Support nullables as function params and return types

---

kt/godot-library/src/main/kotlin/godot/extensions.kt
kt/godot-library/src/main/kotlin/godot/global/GD.kt
kt/godot-library/src/main/kotlin/godot/global/GDCore.kt
kt/godot-library/src/main/kotlin/godot/global/GDMath.kt
kt/godot-library/src/main/kotlin/godot/global/GDPrint.kt
kt/godot-library/src/main/kotlin/godot/global/GDRandom.kt
kt/godot-runtime/src/main/kotlin/godot/core/GarbageCollector.kt
kt/godot-runtime/src/main/kotlin/godot/util/Utils.kt

This adds the GD singleton and extensions @CedNaru implemented for the `godot-kotlin` project.

Add GD singleton and extensions

---

src/gd_kotlin.cpp
src/kotlin_language.cpp

This resolves #76 and resolves #81

Fix editor crashes

---

README.md

Kotlin/kotlin
JVM/JVM
Java/java
Small changes to bring consistent capitalisation in the Readme file.

Consistent capitalisation

---

docs/src/doc/getting-started/project-setup.md
docs/src/doc/index.md

Add documentation about where to get the pre built engine

---

.github/workflows/create-draft-release.yaml

This adds a description to our releases, stating what the pre built editor files are and for what the other files are for.

Add release description

---

docs/src/doc/getting-started/add-first-class.md
docs/src/doc/user-guide/api-differences.md
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
kt/plugins/godot-intellij-plugin/src/main/resources/template/Simple.kt.template

Add example class to template

---

docs/src/doc/user-guide/exporting.md

Fix formatting of export documentation

---

harness/benchmarks/build.gradle.kts
harness/benchmarks/project.godot
harness/benchmarks/settings.gradle.kts
harness/bunnymark/build.gradle.kts
harness/bunnymark/runAll_release.sh
harness/bunnymark/settings.gradle.kts

This updates `benchmarks` and `bunnymark` so they are on par with `tests` again setup-wise.

Update other harness projects

---

kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt

Fix service file generation

---

kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt
kt/plugins/godot-intellij-plugin/build.gradle.kts
kt/plugins/godot-intellij-plugin/detekt-config.yml
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
kt/plugins/godot-intellij-plugin/src/main/resources/template/build.gradle.kts.submodule.template

Fix module wizard submodule handling

---

harness/tests/src/main/kotlin/godot/tests/coretypes/StringTest.kt
harness/tests/test/unit/test_string.gd
kt/godot-runtime/src/main/kotlin/godot/core/Variant.kt
src/kt_variant.h

Remove 0 at end of strings.

---

kt/buildSrc/src/main/kotlin/godotKotlinJvmVersion.kt

This upgrade version for new release.

feat: Update godot kotlin version to 0.2.0

---

harness/tests/build.gradle.kts
kt/api-generator/build.gradle.kts
kt/buildSrc/build.gradle.kts
kt/buildSrc/src/main/kotlin/DependenciesVersions.kt

This updates the kotlin version and the KSP version used to kotlin `1.5.21`

Update to kotlin `1.5.21`

---

kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/listener/KtPsiTreeListener.kt

Fix plugin crash on refactoring

---

.github/workflows/check-pr-intellij-plugin.yaml
.github/workflows/deploy-intellij-plugin.yaml
kt/plugins/godot-intellij-plugin/build.gradle.kts

Update idea plugin

---

kt/plugins/godot-intellij-plugin/src/main/resources/template/build.gradle.kts.submodule.template
kt/plugins/godot-intellij-plugin/src/main/resources/template/build.gradle.kts.template
kt/plugins/godot-intellij-plugin/src/main/resources/template/gradle-wrapper.properties.template

This fixes project templates for projects created with our project wizard.

Fix project templates

---

docs/requirements.txt

Quick PR to solve problems on pipeline.

chore: update mkdocs to 1.3.0

---

harness/tests/build.gradle.kts
kt/api-generator/build.gradle.kts
kt/buildSrc/build.gradle.kts
kt/buildSrc/src/main/kotlin/DependenciesVersions.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/filebuilder/ClassRegistrarFileBuilder.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/filebuilder/MainEntryFileBuilder.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/ExpRangeHintStringGenerator.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/IntRangeHintStringGenerator.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/LongRangeHintStringGenerator.kt
kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/compiler/KtCallExpressionExtractor.kt
kt/settings.gradle.kts

As discussed on Discord; this updates the kotlin version and our main dependencies for the next 3.x release as well.

Update project; kotlin version to `1.7.0`, shadowJar to `7.1.2`, kotlinPoet to `1.12.0`, ksp to `1.7.0-1.0.6`

---

docs/mkdocs.yml
docs/src/doc/user-guide/advanced/abstract_classes.md
harness/tests/project.godot
harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceChild.kt
harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceParent.kt
harness/tests/test/unit/test_inheritance_abstract.gd
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/filebuilder/ClassRegistrarFileBuilder.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/PropertyRegistrationGenerator.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/Clazz.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/RegisteredClass.kt
kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/ext/ksClassDeclarationExt.kt
kt/plugins/godot-intellij-plugin/detekt-config.yml
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/clazz/RegisterClassAnnotator.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/function/RegisterFunctionAnnotator.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/codevision/RegisteredNameInlayHint.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/FunctionNotRegisteredQuickFix.kt
kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties

* Implement support for abstract classes
* Add abstract classes documentation
* Ignore default parameters in detekt config for too many function parameters
* Add IDE check for not registered overridden abstract functions which were registered in the abstract class

Support abstract classes (#339)

---

README.md

fix: set right contribution guideline in readme

---

harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceEmptyChild.kt
harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceEmptyParent.kt
kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/ext/ksClassDeclarationExt.kt

Fix registration of empty abstract classes extending godot classes

---

kt/plugins/godot-gradle-plugin/build.gradle.kts
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/setupTasks.kt
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/generateGdIgnoreFilesTask.kt
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/setupBuildTask.kt
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/setupCleanTask.kt
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/setupSyncTask.kt

Resolves #220.
Still a draft PR, because i have issues with our class registration inside the godot editor in general atm and cannot properly test this Impl.
Will be resolved after our meeting from today i hope.

Generate `.gdignore` files for the `build` and the `gradle` directories

---

kt/build.gradle.kts

This changes the changelog header to be more explicit in what files have what purpose.

Improve changelog header

---

kt/godot-library/src/main/kotlin/godot/core/Rect2.kt
kt/godot-library/src/main/kotlin/godot/core/Rect2i.kt
kt/godot-library/src/main/kotlin/godot/core/Vector2i.kt

This implements `Rect2I` core type kotlin class.

feat: implement Rect2i core type kotlin class

---

kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt

This adds missing core types to entry generator.  
This is a quick fix PR, we reaally will need to share code between entry gen and api gen.

fix: Add missing core types to entry generator.

---

kt/api-generator/src/main/kotlin/godot/codegen/constants/Classes.kt

This adds new core types to api generator.

bugfix(4.0): Add new core types to api generation

---

src/kotlin_language.cpp

is this enough to add syntax highlighting?
blessings 🙏🏻

add value keyword

---

harness/tests/gradle/wrapper/gradle-wrapper.properties
harness/tests/settings.gradle.kts
kt/api-generator/build.gradle.kts
kt/godot-library/build.gradle.kts
kt/gradle/wrapper/gradle-wrapper.properties
kt/plugins/godot-dependencies-gradle-plugin/build.gradle.kts
kt/plugins/godot-dependencies-gradle-plugin/src/main/kotlin/godot/dependencies/gradle/DependenciesVersions.kt
kt/plugins/godot-gradle-plugin/build.gradle.kts
kt/plugins/godot-intellij-plugin/build.gradle.kts
kt/plugins/godot-intellij-plugin/src/main/resources/template/gradle-wrapper.properties.template
kt/plugins/godot-publish-gradle-plugin/build.gradle.kts
kt/plugins/godot-publish-gradle-plugin/src/main/kotlin/godot/publish/gradle/mavencentral/PublishToMavenCentralPlugin.kt
kt/tools-common/build.gradle.kts

This makes the project compatible with gradle version 8 and increases the supported kotlin version to `1.8.10`

Gradle 8 compatibility

---

kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/EntryGenerator.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/checks/FunctionArgCountCheck.kt

This adds a similar check to function argument counts as we already have for constructors

Add function args count check

---

.github/workflows/check-pr-intellij-plugin.yaml
.github/workflows/deploy-intellij-plugin.yaml
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/checks/DefaultConstructorCheck.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/RegisteredClass.kt
kt/godot-library/src/main/kotlin/godot/extensions/NodeExt.kt
kt/godot-library/src/main/kotlin/godot/extensions/StringExt.kt
kt/godot-library/src/main/kotlin/godot/extensions/StringNameExt.kt
kt/plugins/godot-intellij-plugin/build.gradle.kts

Fix various small issues

---

CMakeLists.txt
src/gd_kotlin.cpp
src/kt_class.cpp
src/type_manager.cpp

This makes use of `DEV_ENABLED` cpp definition.

enh: Use DEV_ENABLED definition in cpp code

---

docs/src/doc/user-guide/versioning.md
kt/gradle/libs.versions.toml
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/ios/createIOSGraalNativeImage.kt

fix(gradle-plugin): add star projection on command line to build ios native image

---

harness/tests/otherSourceDir/CopyModificationCheckTestClass.kt
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/properties/GodotKotlinJvmPropertiesFileImpl.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/copy/CopyModificationAnnotator.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/gradle/GradleCompatibility.kt
kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties
kt/plugins/godot-plugins-common/src/main/kotlin/godot/plugins/common/GodotKotlinJvmPropertiesFile.kt

This re enables our core type copy modification checks and improves them significantly.
This also fixed plugin compatibility checks and improves some error messages.

Core type checks and error reporting improvements

---

kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt

Fix icon.svg generation in IDE plugin

---

docs/src/doc/index.md
kt/gradle/libs.versions.toml

This updates the kotlin version to `1.9.23` and updates ksp to `1.9.23-1.0.19`

Bump kotlin version to 1.9.23

---

src/kotlin_editor_export_plugin.cpp
src/kotlin_editor_export_plugin.h
src/logging.h
src/resource_format/jvm_resource_format_loader.cpp
src/type_manager.cpp
src/type_manager.h

Two issues were solved :
- I forgot to fill the map that link source files to names in release mode.
- Source files were exported with a different extension and not picked up by our custom loader.
I tested:
- Windows Editor (with reloading)
- Windows Export
- Android Export

Fix export

---

harness/bunnymark/Benchmarker.gd
harness/bunnymark/project.godot
harness/bunnymark/settings.gradle.kts
kt/godot-library/src/main/kotlin/godot/core/Variant.kt
kt/godot-library/src/main/kotlin/godot/core/callable/KtCallable.kt
kt/godot-library/src/main/kotlin/godot/core/memory/MemoryManager.kt
kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/godot-kotlin-graal-jni-config.json
src/gd_kotlin.cpp
src/jni/env.cpp
src/jni/env.h
src/jni/types.cpp
src/jni/types.h
src/jni/wrapper.h
src/jvm_wrapper/memory/transfer_context.cpp
src/jvm_wrapper/registration/kt_function.cpp
src/jvm_wrapper/registration/kt_function.h
src/jvm_wrapper/registration/kt_property.cpp

Rework Memory manager to make it more threadsafe.

---

.github/workflows/assemble_ios.yml

This fixes ios template directory layout.

fix: proper ios template directory layout

---

.github/workflows/build_android.yml
.github/workflows/build_ios.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml

This fixes the scons cache action path. Should fix the ci/cd cache issue we're having recently

Fix scons cache action path

---

docs/src/doc/user-guide/exporting.md
harness/tests/build.gradle.kts
kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
versionBumpGuide.txt

This also bumps the referenced versions across our project

Update documentation regarding minimum android build-tool version

---

kt/godot-coroutine-library/build.gradle.kts

This fixes the gradle task setup of the new coroutines library

Fix gradle task setup

---

docs/src/doc/user-guide/api-differences.md
kt/godot-library/src/main/kotlin/godot/core/bridge/NodePath.kt
kt/godot-library/src/main/kotlin/godot/core/memory/MemoryManager.kt

In #696, I forgot to update the doc and rename the caching method for NodePath.

Update doc regarding caching

---

README.md

Just a little upgrade so the discord and documentation are more visible on the page.

Adding badges to the readme.

---

.github/workflows/build_jvm.yml
kt/.gitignore
kt/build.gradle.kts
kt/gradle/libs.versions.toml
kt/plugins/godot-intellij-plugin/build.gradle.kts
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/property/PropertyHintAnnotationChecker.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/reference/CallFunctionReferenceChecker.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/reference/SignalFunctionReferenceChecker.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/gradle/GodotKotlinJvmSettings.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/gradle/GradleSystemListener.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/listener/PsiTreeListener.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/listener/refactoring/RefactoringListenerProvider.kt
kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/ClassAlreadyRegisteredQuickFix.kt
kt/plugins/godot-intellij-plugin/src/main/resources/META-INF/plugin.xml
kt/plugins/godot-plugins-common/build.gradle.kts
kt/plugins/godot-plugins-common/src/main/kotlin/godot/plugins/common/gradle/action/FetchProjectModelsBuildAction.kt

This updates our IDE plugin to 2024.2 and updated the gradle setup to use the new [intellij platform gradle plugin](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html)

Update IDE plugin to 2024.2

---

README.md
docs/src/doc/index.md

This updates our project and readme to declare this project's status being `Beta`

Declare project status as beta

---

.github/workflows/build_macos.yml
install_vulkan_sdk_macos.sh

Temporary fix until we have a new Godot stable release.

Fix macos build

---

docs/src/doc/getting-started/requirements.md
src/gd_kotlin.cpp

Clarify JAVA_HOME for MacOS users

---

harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceParent.kt
kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/PropertyHintStringGeneratorProvider.kt

Fix hint annotation check for hints higher up in class hierarchy

---

kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/Dictionary.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/AABB.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Basis.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Color.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Projection.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Quaternion.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Rect2.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Transform2D.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Transform3D.kt
kt/godot-library/godot-core-library/src/main/kotlin/godot/core/math/Vector3.kt
kt/godot-library/godot-core-library/src/test/kotlin/godot/core/BasisTest.kt
kt/godot-library/godot-core-library/src/test/kotlin/godot/core/ColorTest.kt
kt/godot-library/godot-core-library/src/test/kotlin/godot/core/ProjectionTest.kt
kt/godot-library/godot-core-library/src/test/kotlin/godot/core/QuaternionTest.kt
kt/godot-library/godot-core-library/src/test/kotlin/godot/core/Rect2Test.kt
src/jvm_wrapper/bridge/dictionary_bridge.cpp
src/jvm_wrapper/bridge/dictionary_bridge.h

Update core types

---

src/jvm_wrapper/bridge/packed_vector2_array_bridge.cpp
src/jvm_wrapper/bridge/packed_vector3_array_bridge.cpp
src/jvm_wrapper/bridge/packed_vector4_array_bridge.cpp

Merging the new VariantAllocator and adding new methods allocating a PackedArray  in a 2 separate PR open at the same time wasn't the best idea...

Fix PackedVectorArray allocation

---

harness/tests/src/main/java/godot/tests/JavaTestClass.java
kt/api-generator/src/main/kotlin/godot/codegen/generation/rule/EnumRule.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/Control.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/FileAccess.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/ImageFormatLoader.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/Mesh.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/NavigationPathQueryParameters2D.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/NavigationPathQueryParameters3D.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/Node.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/OpenXRInterface.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/RenderingDevice.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/RenderingServer.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/ResourceSaver.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/RetargetModifier3D.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/RichTextLabel.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/TextServer.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/XRBodyModifier3D.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/XRBodyTracker.kt
kt/godot-library/godot-api-library/src/main/kotlin/godot/api/XRHandTracker.kt
kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/KeyModifierMask.kt
kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/MethodFlags.kt
kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/MouseButtonMask.kt
kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/PropertyUsageFlags.kt

Otherwise, not visible to Java/Scala

Don't inline bitfields
