- src/kt_signal_info.cpp
- src/kt_signal_info.h
This fixes memory leak at engine closing regarding arguments in KtSignalInfo.
> Fix memory leak of KtSignalInfo arguments

- kt/plugins/godot-intellij-plugin/detekt-config.yml
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/clazz/RegisterClassAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/data/cache/classname/RegisteredClassNameCache.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/data/cache/classname/RegisteredClassNameCacheProvider.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/data/cache/signalconnection/SignalConnectionCache.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/data/cache/signalconnection/SignalConnectionCacheProvider.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/linemarker/SignalConnectionLineMarker.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/listener/GodotSceneBulkFileListener.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/listener/KtPsiTreeListener.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/ClassAlreadyRegisteredQuickFix.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/refactor/SceneAction.kt
This implements support for script moving from within intellij.
When a registered class is moved inside Intellij all occurrences of that class in all scene files (`tscn` only) are now updated as well.
> Implement script move refactoring support for scene files

- kt/entry-generation/godot-annotation-processor/src/main/kotlin/godot/annotation/processor/GodotAnnotationProcessor.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/clazz/RegisterClassAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/function/RegisterFunctionAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/property/PropertyHintAnnotationChecker.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/property/RegisterPropertiesAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/signal/RegisterSignalAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/data/model/annotations.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/ClassNotRegisteredQuickFix.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/NotificationFunctionNotRegisteredQuickFix.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/RegisterSignalInitializerQuickFix.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties
Currently the class registration has some important limitations:
- Only one class per file can be registered
- The file name has to match the class name
- The package path has to match the folder structure
This PR implements additional checks for both compiler plugin (to let the compilation fail if one of the above mentioned is not fulfilled) and for the intellij plugin (to provide error messages in the IDE).
Depends on: https://github.com/utopia-rise/godot-kotlin-entry-generator/pull/13
> Add additional checks in intellij plugin and compiler plugin

- kt/entry-generation/godot-annotation-processor/src/main/kotlin/godot/annotation/processor/GodotAnnotationProcessor.kt
- kt/entry-generation/godot-kotlin-compiler-plugin-common/src/main/kotlin/godot/kotlincompilerplugin/common/CompilerPluginConst.kt
- kt/entry-generation/godot-kotlin-compiler-plugin/src/main/kotlin/godot/kotlincompilerplugin/CommonComponentRegistrar.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/setupConfigurationsAndCompilations.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/util/fileExt.kt
This fixes incremental builds on windows.
They were broken as the code i was using to get all the source code from a project could not find any source code files as all absolute paths of kotlin source code directories of windows end in `;C`. But only kotlin source directories. All other directories including java source directories not. WTF????
Anyways. By removing that suffix from the absolute path's, the files can be found and the incremental builds also work for windows.
Edit:
Found another problem, the cleanup as deleting to many files because of wrong file separator usage. Fixed that as well.
> Fix incremental builds on windows

- harness/tests/build.gradle.kts
- harness/tests/project.godot
- harness/tests/scripts/ScriptInOtherSourceDir.kt
- harness/tests/test/unit/test_custom_src_dir.gd
- src/gd_kotlin.cpp
- src/gd_kotlin.h
- src/kotlin_language.cpp
This replaces https://github.com/utopia-rise/godot-jvm/pull/58 as the changes on the master were to great to change the old PR and many things from it were not needed anymore.
This adds support for custom source dirs.
Not necessarily needed but the name registration fix of the entry gen should be merged first.
https://github.com/utopia-rise/godot-kotlin-entry-generator/pull/19
> Implement support for custom srcDirs

- README.md
- docs/SUMMARY.md
- docs/mkdocs.yml
- docs/src/doc/advanced/commandline-args.md
- docs/src/doc/advanced/custom-src-dirs.md
- docs/src/doc/api-differences.md
- docs/src/doc/index.md
- docs/src/doc/pre-alpha.md
This adds more documentation geared towards the pre-alpha "release".
~~Please look again through the `Api-Differences` page as i don't think it is correct (regarding the value by copy vs value by reference). I would change it in this PR if incorrect.~~ fixed
> Pre-Alpha docs

- kt/godot-runtime/src/main/kotlin/godot/runtime/Bootstrap.kt
This resolves #67 
Before we were loading all engine types on each rebuild while the editor was open. This is not necessary as they will never change in the time the editor is open.
This only loads them once for the runtime of an application.
> Only load engine types once

- harness/tests/src/main/kotlin/godot/tests/Invocation.kt
- kt/godot-library/src/main/kotlin/godot/extensions.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/Object.kt
- kt/godot-library/src/main/kotlin/godot/signals/Signals.kt
Depends on https://github.com/utopia-rise/godot-kotlin-api-generator/pull/3 and fixes the following extension methods:
- `getNode<T>` now also allows nullable types
- `Signal<T>.connect` now correctly returns `GodotError`
> Fix some extension methods

- docs/src/doc/api-differences.md
- docs/src/doc/user-guide/classes.md
During discussions on discord regarding #99 we noticed that the documentation does not yet cover the limitations about the usage of the Godot Api from within constructor blocks.
This fixes it.
> Include limitations of constructor block

- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/clazz/RegisterClassAnnotator.kt
This fixes the package path check in the IDE plugin for windows.
> Fix package path check on windows

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt
I guess through a rebasing error when merging the android support, the limitation of only applying our plugin to the gradle root project got reintroduced. This fixes it by removing that line again.
I could not find any other issues yet. But I'll keep an eye on that.
> Remove root project requirement (again)

- harness/tests/build.gradle.kts
- harness/tests/settings.gradle.kts
- kt/buildSrc/src/main/kotlin/DependenciesVersions.kt
- kt/buildSrc/src/main/kotlin/godotKotlinJvmVersion.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
This fixes the entry gen version which was wrong in the previous alpha release attempt.
New version will be `0.1.1-3.2.3`
> Fix entry gen version and bump version codes

- src/jni/jvm_loader.cpp
We were using `getenv` method from `stdlib` to get `JAVA_HOME` environment variable.  
This method is deprecated.  
To avoid problems and potential bugs on finding `JAVA_HOME`, this makes use of `OS` singleton.
> Fix: Use OS singleton instead of stdlib to get JAVA_HOME env variable

- docs/src/doc/alpha.md
- docs/src/doc/index.md
- docs/src/doc/user-guide/signals.md
This fixes wrong links to the api differences page. Noticed by user `cris-null` on discord: https://discord.com/channels/675058327088136212/675367449184698378/832421575013171220
> Fix api differences links

- kt/godot-runtime/src/main/kotlin/godot/core/Properties.kt
- kt/godot-runtime/src/main/kotlin/godot/runtime/Bootstrap.kt
- kt/godot-runtime/src/main/kotlin/godot/runtime/Registration.kt
- src/bootstrap.cpp
- src/bootstrap.h
- src/gd_kotlin.cpp
- src/gd_kotlin.h
- src/kt_class.cpp
- src/kt_class.h
This fixes a bug where, when a class has properties with default values which are other user scripts, and this class is registered after the other class, the editor/game would crash at startup:
```
Godot-JVM: Registered _VisualScriptEditor engine type with index 621.
Godot-JVM: Done registering managed engine types...
ERROR: get: FATAL: Index p_index = 6 is out of bounds (size() = 0).
At: ./core/cowdata.h:152.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /home/cedric/projects/04_godot/modules/kotlin_jvm/harness/tests/jre/lib/server/libjvm.so(+0xbe1f66) [0x7f96159eff66] (??:0)
[2] /home/cedric/projects/04_godot/modules/kotlin_jvm/harness/tests/jre/lib/server/libjvm.so(JVM_hand …
```
> Fix default values of user script types

- .github/workflows/create-draft-release.yaml
- kt/build.gradle.kts
Resolves #152 
This generates the changelog for releases.
example for `0.1.3`:
```markdown
The pre built engines are the zip files.  
The other files are export templates needed for exporting your game. See [exporting](https://godot-kotl.in/en/latest/user-guide/exporting/) documentation on how to use them.
**Changelog:**
- [07113b1](https://github.com/utopia-rise/godot-kotlin-jvm/commit/07113b1dd0e07ef9b03061fa9d1c7d2403cea99b) Update versions for release (#150)
- [a5b88d7](https://github.com/utopia-rise/godot-kotlin-jvm/commit/a5b88d7876a338d0d1c3223590ed6f094e293c0f) Hotfix/fix from godot to kotin basis (#142)
- [ff3d16a](https://github.com/utopia-rise/godot-kotlin-jvm/commit/ff3d16ac7af4075440eec6aa37c508e304dc80cd) Fix default values of user script types (#137)
- …
```
> Generate changelog

- harness/benchmarks/gradle/wrapper/gradle-wrapper.properties
- harness/bunnymark/gradle/wrapper/gradle-wrapper.properties
- kt/buildSrc/build.gradle.kts
- kt/buildSrc/src/main/kotlin/DependenciesVersions.kt
- kt/entry-generation/godot-annotation-processor/build.gradle.kts
- kt/entry-generation/godot-kotlin-entry-generator/build.gradle.kts
- kt/entry-generation/godot-kotlin-entry-generator/src/main/kotlin/godot/entrygenerator/EntryGenerator.kt
- kt/entry-generation/godot-kotlin-entry-generator/src/main/kotlin/godot/entrygenerator/generator/function/FunctionRegistrationGenerator.kt
- kt/godot-bootstrap/build.gradle.kts
- kt/godot-library/src/main/kotlin/godot/extensions.kt
- kt/godot-library/src/main/kotlin/godot/signals/SignalProvider.kt
- kt/godot-runtime/src/main/kotlin/godot/core/Dictionary.kt
- kt/godot-runtime/src/main/kotlin/godot/core/GarbageCollector.kt
- kt/godot-runtime/src/main/kotlin/godot/core/Properties.kt
- kt/godot-runtime/src/main/kotlin/godot/core/Variant.kt
- kt/godot-runtime/src/main/kotlin/godot/core/VariantArray.kt
- kt/godot-runtime/src/main/kotlin/godot/runtime/Registration.kt
- kt/godot-runtime/src/main/kotlin/godot/util/IndexedIterator.kt
- kt/godot-runtime/src/main/kotlin/godot/util/Utils.kt
- kt/plugins/godot-gradle-plugin/build.gradle.kts
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/setupConfigurationsAndCompilations.kt
This updates all our dependencies to the latest versions (except api gen as it's still an external project).
This also resolves or supresses all compiler warnings except those fixed in different PR's (for example enumLists in #165) or features which are not yet implemented (for example tool mode).
Gradle could not yet be updated to 7.0 because of https://youtrack.jetbrains.com/issue/KT-46165
> Update dependencies and fix compiler warnings

- .github/workflows/deploy-docs.yaml
Resolves #182.
This just marks the current non-snapshot tag as stable (i.e creating a tag named stable). The old tag will be deleted first. RTD is now configured to use the stable tag as default.
> Add ci step to mark latest version as stable

- harness/tests/src/main/kotlin/godot/tests/FuncRefTest.kt
- harness/tests/src/main/kotlin/godot/tests/Invocation.kt
- kt/godot-library/src/main/kotlin/godot/extensions/NodeExt.kt
- kt/godot-library/src/main/kotlin/godot/extensions/ObjectExt.kt
Extensions are now in their own package and I split them into 2 files, one for Object, one for Node.
Also because of a conflict with the "getNode" name, the helpers have been rename simple "node".
related issue : #183
> Rename node helpers

- src/kotlin_language.cpp
- src/kotlin_script.cpp
Fix #177 
The package name is inferred from the file path of the newly created script.
For now, it only works if you the main source directory.
A package name will still be written if you use a custom source dir but it won't be correct. Unless we find a way to set the path of the custom dir in the C++ code I can't fix that particular case.
If the script is at the root of the source directory no package is written at all as well, as it should be.
> Scripts created from Godot have a package set.

- src/bridges/variant_array_bridge.cpp
Resolve #206 
The reason was that some Variants were cast to Object* when the method wanted a Variant.
So every Variant that didn't hold an Object was returning a null.
That's why `arr[x] = y` with y different than Object was not working
> Fix VariantArray set

- .github/workflows/deploy-export-template-debug.yaml
- .github/workflows/deploy-export-template-release.yaml
- .github/workflows/deploy-godot-annotation-processor.yaml
- .github/workflows/deploy-godot-editor-release.yaml
- .github/workflows/deploy-godot-kotlin-compiler-plugin.yaml
- .github/workflows/deploy-godot-library.yaml
- .github/workflows/deploy-godot-runtime.yaml
Godot version is inconsistent, this cause trouble to deploy new release.
Quick fix is to hardcode version in CI.
> Fix: Harcode godot version in CI as it is inconsistency

- kt/api-generator/src/main/kotlin/godot/codegen/Property.kt
- kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/BitmapFont.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/CanvasItem.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/CurveTexture.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/ExternalTexture.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/Font.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/GradientTexture.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/InputEventAction.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/InputEventJoypadButton.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/InputEventKey.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/InputEventMouseButton.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/InputEventScreenTouch.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/Node2D.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/NoiseTexture.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/Texture.kt
Generated getters were not calling parent method if method was starting with `is`.
This resolves #216
> fix: Getter now calls method from parent even if getter starts with is

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/setupConfigurationsAndCompilations.kt
With #244 I forgot to also generate the service file again. Previously we've done that in the entry gen. But the way this was done lead to #232.
The service file is now generated from within the gradle plugin rather than the entry gen as this makes more sense IMO as the gradle plugin is the one with the project information.
With this PR we generate the service file again and also resolve #232.
> Fix generation of service file

- .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
- .github/workflows/check-pr-engine-editor-release.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
- .github/workflows/deploy-export-template-debug.yaml
- .github/workflows/deploy-export-template-release.yaml
- .github/workflows/deploy-godot-editor-release.yaml
This is done because one should use the oldest distro version one wants to support, to build linux binaries. Like this we ensure the binaries are downwards compatible until the version we built the binary with.
Resolves #224
> Use `ubuntu-18.04` to build linux binaries

- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/PropertyRegistrationGenerator.kt
Fixes #243.
When implementing the entry generator with ksp i forgot to register the JVM_* types as their actual godot type rather than their KtVariant type. This lead to the inspector not showing properties with the types `Int`, `Float` and `Byte`.
This PR fixes this.
> Fix jvm type registration

- docs/mkdocs.yml
- docs/src/doc/index.md
- docs/src/doc/user-guide/advanced/gradle-plugin-configuration.md
- harness/tests/build.gradle.kts
- harness/tests/gradle.properties
- kt/buildSrc/src/main/kotlin/DependenciesVersions.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/template/build.gradle.kts.submodule.template
- kt/plugins/godot-intellij-plugin/src/main/resources/template/build.gradle.kts.template
- kt/utils/godot-build-props/build.gradle.kts
- kt/utils/godot-build-props/src/main/kotlin/godot/utils/GodotBuildProperties.kt
- kt/utils/godot-build-props/src/main/resources/build.properties
This resolves #208.
The kotlin jvm plugin is now applied by our gradle plugin by default. If a kotlin version is already applied (either by the user explicitly applying the kotlin jvm plugin by himself or through something like `buildSrc`), then we check the applied kotlin version and let the build fail if the detected kotlin version is not the one we're expecting/supporting.
As there are cases were an advanced user is familiar with kotlin compiler plugin constraints and still wants to use another kotlin version, one can suppress the version check by specifying `godot.jvm.suppressKotlinIncompatibility=true` in the `gradle.properties` file.
> Kotlin version checks in gradle plugin

- src/transfer_context.cpp
- src/transfer_context.h
We were missing some safety in `TransferContext` when converting jlong to ptr.
> fix: Add safety to transfer context long to ptr conversions.

- .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
- .github/workflows/check-pr-engine-editor-release.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
For now this only contains addition of macos arm64 for check CI.  
I'll do the deploy workflow on another PR as I need a fork to test it.
> feature: Add macos arm64 check CI

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/createMainDexFileTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageBootstrapDexJarTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/createGraalNativeImage.kt
Fixes task setup errors for `exec` based tasks which i introduced with #263.
#270 already contains this fix, but as it could take a while to merge; here's a dedicated hotfix.
> Fix `exec` task setup

- harness/tests/src/main/kotlin/godot/tests/FuncRefTest.kt
- harness/tests/test/unit/test_funcref.gd
- kt/godot-library/src/main/kotlin/godot/extensions/ObjectExt.kt
> bugfix: explode vararg array in call extensions

- kt/godot-library/build.gradle.kts
The fat jar is only needed for the editor release and is added to it through the github workflow.
The maven publication on the other hand only needs the non fat jar version.
This was previously handled through the dedicated `godot-bootstrap` module, and the module `godot-library` did formerly not contain any `shadowJar` task hence there was not a conflict with possible jars to publish. This is fixed by now explicitly setting the non shadow task output as the publish artifact.
> Fix godot-library publication by only including non fat jar in actual publication

- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/GodotAnnotation.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/ext/ksAnnotationExt.kt
This fixes a crash during compilation when an unknown annotation is encountered.
This was initially intended to catch missing/not implemented godot annotations but it also crashes on any third party annotation being processed by our symbol processor.
In the future we should also model third party annotations in our source code abstraction so they can be used in entry gen extensions. But as they are something for the distant future, we just ignore unknown annotations for now.
> Fix ksp crash on unknown annotation

- docs/src/doc/user-guide/exporting.md
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/createMainDexFileTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageBootstrapDexJarTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageMainDexJarTask.kt
Add androidMinApi parameter to gradle plugin to enable specify --min-api argument of d8 tool
> feature: enable to set android min api

- kt/buildSrc/src/main/kotlin/DependenciesVersions.kt
- kt/plugins/godot-gradle-plugin/build.gradle.kts
Security: Update shadow plugin dependency to 7.1.2, in order to address [CVE-2021-45105](https://github.com/advisories/GHSA-p6xc-xr62-6r2g) and [CVE-2021-44832](https://github.com/advisories/GHSA-8489-44mv-ggj8)
> Security: Update shadow plugin dependency to 7.1.2

- .github/workflows/check-pr-intellij-plugin.yaml
- .github/workflows/deploy-intellij-plugin.yaml
- docs/src/doc/index.md
- docs/src/doc/user-guide/versioning.md
- harness/tests/build.gradle.kts
- kt/api-generator/build.gradle.kts
- kt/buildSrc/build.gradle.kts
- kt/buildSrc/src/main/kotlin/DependenciesVersions.kt
- kt/buildSrc/src/main/kotlin/godotKotlinJvmVersion.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/compiler/KtCallExpressionExtractor.kt
- kt/plugins/godot-intellij-plugin/build.gradle.kts
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/property/KtExpressionConstantChecker.kt
This updates module to kotlin `1.6.21`.  
This adds deployment of intellij plugin for version `2021.3`.  
This bumps module version to `0.3.5`
> Feature/update to kotlin 1.6.21 and add deployment IJ213 intellij plugin

- .github/workflows/check-pr-intellij-plugin.yaml
- .github/workflows/deploy-intellij-plugin.yaml
- kt/plugins/godot-intellij-plugin/build.gradle.kts
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/copy/CopyModificationAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/reference/RSetPropertyReferenceChecker.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/reference/RpcFunctionReferenceChecker.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/listener/KtPsiTreeListener.kt
Resolves #332 
This updates our IDE plugin to support `2022.x` versions of `IDEA`.
This also defines a more lenient supported max version so we hopefully don't have to update the plugin as often.
For more information, see either the Discord discussion or the documented outcome in #332.
> Update IDE plugin and define a more lenient supported max version

- docs/mkdocs.yml
- docs/src/doc/user-guide/advanced/abstract_classes.md
- harness/tests/project.godot
- harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceChild.kt
- harness/tests/src/main/kotlin/godot/tests/inheritance/AbstractClassInheritanceParent.kt
- harness/tests/test/unit/test_inheritance_abstract.gd
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/filebuilder/ClassRegistrarFileBuilder.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/PropertyRegistrationGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/Clazz.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/RegisteredClass.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/ext/ksClassDeclarationExt.kt
- kt/plugins/godot-intellij-plugin/detekt-config.yml
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/clazz/RegisterClassAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/function/RegisterFunctionAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/codevision/RegisteredNameInlayHint.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/quickfix/FunctionNotRegisteredQuickFix.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties
This adds support for member registration in abstract classes.
Now one can define abstract classes which inherit from a godot type and register default members in it.
Upon registration of inheriting classes, the inheriting class registers the member of the abstract class as well.
To godot, the abstract class does not exist as it's not registered. But on the jvm side, it exists and all calls to the default members are properly propagated through normal inheritance.
Example:
```kotlin
// register class annotation is optional for abstract classes
abstract class AbstractClassInheritanceParent: Node() {
@Export
@RegisterProperty
var registeredExportedPropertyInAbstractClass = false
@RegisterSignal
val signalInAbstractClass by signal<String>("blubb")
@RegisterFunction
fun …
```
> Support abstract classes

- kt/api-generator/src/main/kotlin/godot/docgen/rawXmlPojos.kt
Fixes generation of invalid doc generation.
Only relevant for Godot `3.x` branch (so next 3.x release) hence the merge target is develop.
In Godot `3.x` branch this new invalid comment sequence appears in the `InputMap.getActionList` documentation.
> Fix invalid comment sequence in doc gen

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageMainDexJarTask.kt
- src/gd_kotlin.cpp
It seems almost a year ago I broke android export.  
`main-dex.jar` was not copied to user dir anymore.  
Service file was not included in android dex main jar anymore.
> bugfix: android dex jar loading

- .github/workflows/deploy-export-template.yaml
- .github/workflows/deploy-godot-editor-release.yaml
- kt/build.gradle.kts
This creates macOs editor universal app on release instead of binaries per architecture.
> feat: Create MacOs editor app on release

- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/clazz/RegisterClassAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/function/RegisterFunctionAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/general/checkNotGeneric.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/property/RegisterPropertiesAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/signal/RegisterSignalAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties
This check verifies that the user does not try to register any generic types as these won't compile.
Resolves #372
> Implement generics check in IDE plugin

- .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
- .github/workflows/check-pr-engine-editor-release.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
- .github/workflows/check-pr-godot-kotlin-symbol-processor.yaml
- .github/workflows/deploy-export-template.yaml
- .github/workflows/deploy-godot-editor-release.yaml
- .github/workflows/deploy-godot-kotlin-symbol-processor.yaml
- .github/workflows/deploy-godot-library.yaml
Godot master branch is always receiving new commit, making code in the module instable as it can break when we pull the master.
From now, we use commit 89a33d28f, the one Godot 4.0 beta 5 is based on.
> Set Godot to 4.0 beta 5 instead of master

- src/kt_class.cpp
- src/kt_class.h
fix #384 
Properties are now set in a OrderedHashMap, so we can retrieve them in the order they were declared in script.
Wonder if signals and functions also require the same treatment. Properties matter for the inspector but I don't think there is an equivalent for the rest. 
Ordered hashmaps are also slower, switching functions to one would slow down calls to the JVM a bit (probably not noticeable but still slower)
> Add Vector of properties in Tool Mode

- harness/tests/build_with_compiler_plugin_debug.sh
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/GodotKotlinSymbolProcessor.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/ext/ksClassDeclarationExt.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/visitor/RegistrationAnnotationVisitor.kt
If a supertype of a class had a compilation error, our symbol processor threw an error as it could not resolve the fully qualified name of said class as it has compilation errors. We then threw a exception in the symbol processor which hides the real problem.
Example:
class with compilation error (note the typo `Nodu` instead of `Node`:
```kotlin
@RegisterClass
class ScriptInOtherSourceDir: Nodu() {
@RegisterFunction
fun greeting() = "HelloWorld"
}
```
Previously this printed the following error:
```
[ksp] java.lang.IllegalArgumentException: Qualified name for class declaration of a registered type or it's super types cannot be null
// stack trace ommited for simplicity
```
Which hides the real issue that there is a typo in the supertype declaration.
With these changes we just print a …
> Fix wrongly reported ksp error upon compilation error

- .github/actions/create-android-export-template/action.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
- .github/workflows/deploy-export-template.yaml
The android x86_64 target is today mainly used for android emulators during development on x86 based host machines because of the increased emulation performance.
They are also a requirement for android apps on windows atm.
> Export android x86_64 target

- .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
- .github/workflows/deploy-export-template.yaml
- .github/workflows/deploy-godot-editor-release.yaml
- CMakeLists.txt
- src/jni/platforms/init_args_desktop.cpp
- src/jni/platforms/jvm_desktop.cpp
This adds support for:
- headless editor builds (useful and needed for exporting games in CI/CD)
- server builds
This PR is a requirement for #370
> Export headless editor and server builds

- harness/tests/src/main/kotlin/godot/tests/constructor/ConstructorRegistrationTest.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/ConstructorRegistrationGenerator.kt
The registration of constructors which have generic type parameters like `Dictionary` was broken.
The following class:
```kotlin
@RegisterClass
class ConstructorRegistrationTest(): Node() {
@RegisterConstructor
constructor(param1: Dictionary<Any, Any?>, param2: VariantArray<Long>): this()
}
```
produced the following invalid constructor registration:
```kotlin
constructor(KtConstructor2({param1: Dictionary<AnyAny?>, param2: VariantArray<Long> -> ConstructorRegistrationTest(param1, param2)}, DICTIONARY to false, ARRAY to false))
```
The reason was that i forgot to add `,` for generic type parameters while assembling the kotlin poet template for the constructor registration. This PR fixes this.
> Fix constructor with generic args registration

- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
- kt/godot-library/src/main/kotlin/godot/core/Functions.kt
- kt/godot-library/src/main/kotlin/godot/core/VariantArray.kt
Fixes #394
This fixes the type hints for resource types.
The issue we were having was two fold:
- For once we did not check the supertypes recursively to detect whether the property was a resource type (in fact the relevant type is `Reference`). We also had that problem for list types. I fixed it there too as well.
- Secondly, since we initially implemented this, two new type hints were added, which meant that the ordinal was not correct anymore. By adding the missing typehints, the ordinal we send to the cpp code is correct again. **Note:** We should investigate if we can either automatically generate these typehint enums, or automatically test whether they are still correct. But I think this is out of the scope for this fix.
> Fix resource property type hint

- kt/godot-library/src/main/kotlin/godot/core/memory/TransferContext.kt
The minimum size for the shared buffer previously depended on Transform, the largest non string type, but that role was overtaken by Projection (4x4 matrix instead of 4x3).
> Minimum size buffer adapted to Projection type

- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/EntryGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/exceptions/WrongAnnotationUsageException.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/FqNameExtensions.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/ColorNoAlphaHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/DirHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/DoubleRangeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/ExpEasingHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/ExpRangeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/FileHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/FloatRangeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/IntFlagHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/IntRangeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/LongRangeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/model/JvmType.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/GodotKotlinSymbolProcessor.kt
- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/utils/JvmTypeProvider.kt
Depends on #432 . (I will change the target branch once that one is merged)
Makes entry gen (hopefully) fully language independent by removing all remaining kotlin fqName checks from it and replacing it by a fqName provider provided to the entry gen by the caller.
With this the entry gen retrieves the fqNames it needs for certain language specific type checks (like "is the fqName i got here an fqName of the Int type or not?") from the caller through the provider.
This should allow the language specific symbol processors to provide the entry gen with the language specific fqNames for the needed types.
> Make entry gen fully language independent

- src/kotlin_script.cpp
This fixes a bug where after a property change in the inspector and saving, the resulting scene file would contain invalid default values for not exported properties.
For example a change on the property `nullable_long` in `Invocation` would also save (wrong) default values for `register_object_nullable_pre_init`, `register_object_non_nullable_pre_init`, `invocation` even though they are not even exported.
This only updates exports (and thus also default values) for properties which are actually exported.
> Fix update export

- .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
- .github/workflows/check-pr-engine-editor-release.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
- .github/workflows/deploy-export-template.yaml
- .github/workflows/deploy-godot-editor-release.yaml
- harness/tests/build.gradle.kts
- harness/tests/export_presets.cfg
- harness/tests/graal/reflect-config.json
- harness/tests/graal/resource-config.json
- harness/tests/src/main/kotlin/godot/tests/reflection/BaseReflectionTest.kt
- harness/tests/test/unit/test_reflection.gd
- kt/godot-library/build.gradle.kts
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/createGraalNativeImage.kt
Resolves #201 
This adds the kotlin reflect library as a transitive dependency to the `godot-library` and thus to the `bootstrap.jar`.
This enables reflection usage in usercode.
It needs to be added to the `godot-library` as the reflection library must be present where the usercode is loaded (`Bootstrap.kt`) in order to work.
Downside is a slight increase in size of the shipped ` bootstrap.jar`  but with around 2MB it's negligible enough IMO.
We could introduce a setting in our gradle plugin which strips the reflection library classes from the final `bootstrap.jar` for exported games but TBH I don't think it's worth the effort and should be "fixed" with #443 anyways.
> Fix reflection usage in usercode

- harness/tests/Spatial.tscn
- harness/tests/src/main/kotlin/godot/tests/Invocation.kt
- harness/tests/test/unit/test_object_node_paths.gd
- harness/tests/test/unit/test_signals.gd
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/NodeTypeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/PropertyHintStringGeneratorProvider.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/typehint/PropertyTypeHintProvider.kt
**Note:** depends on https://github.com/utopia-rise/godot-kotlin-jvm/pull/439. I will change the base of this PR once that one is merged
Resolves: #221 
This adds support for exporting properties with types extending `Node`.
With this a user can directly write
```kotlin
@Export
@RegisterProperty
lateinit var button: Button
```
instead of something like this:
```kotlin
@Export
@RegisterProperty
lateinit var buttonNodePath: NodePath
private val button by lazy { requireNotNull(getNodeAs<Button>(buttonNodePath)) }
```
**Note:** the api checks need to be updated. This will be done together with all other changes in the IDE plugin with #446
> Support exporting of types extending node

- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
This fixes an uninitialized property access exception which occurred when trying to create a new GodotJvm project from the idea project wizard.
Fixes #464
> Fix idea plugin

- docs/src/doc/user-guide/versioning.md
- kt/buildSrc/src/main/kotlin/godotKotlinJvmVersion.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/template/gradle-wrapper.properties.template
This bumps the version on the 3.x branch to `0.6.2` to prepare for another release.
This also sneaks in a little fix for the generated project from the IDE wizard where the gradle version of the gradle wrapper was too old. This just bumps it to the min version in the template.
> [3.x] Bump version to `0.6.2`

- src/memory/transfer_context.cpp
Improves error reporting when calling a method with too many args.
Follow up issue which lead to this PR: #491
> Improve error reporting when calling a method with too many args

- kt/godot-library/src/main/kotlin/godot/core/Constructors.kt
- kt/godot-library/src/main/kotlin/godot/core/KtObject.kt
- kt/godot-library/src/main/kotlin/godot/core/Properties.kt
- kt/godot-library/src/main/kotlin/godot/core/callable/KtCallable.kt
- kt/godot-library/src/main/kotlin/godot/core/memory/TransferContext.kt
- src/memory/transfer_context.cpp
- src/memory/transfer_context.h
Implement #509 
C++:
The idea is simple. Instead of having to call `rewind()` after any operation on the buffer, we simply rewind it as part of the `get_buffer()` method. (The buffer is stored directly inside that method, so it's the only way to get it).
The only manual `rewind()` left is the one in `icall()` as I need to reset it to write the return value.
Kotlin:
I decided to made `TransferContext.buffer` private (doesn't change its visibility from C++ through JNI). I don't think it should be used directly outside TransferContext, so I did a small rework of its methods.
The goal was to remove any manual call to `rewind()` in the rest of the code. Rewinding should be the responsibility of TransferContext alone.
> Rewind() called early in TransferContext

- docs/src/doc/contribution/knowledge-base/shared-buffer.md
- harness/tests/src/main/kotlin/godot/tests/args/FunctionArgSizeTest.kt
- harness/tests/test/unit/test_function_args.gd
- kt/api-generator/src/main/kotlin/godot/codegen/exceptions/TooManyArgument.kt
- kt/api-generator/src/main/kotlin/godot/codegen/models/enriched/EnrichedMethod.kt
- kt/api-generator/src/main/kotlin/godot/codegen/models/enriched/EnrichedSignal.kt
- kt/godot-library/src/main/kotlin/godot/core/Functions.kt
- kt/godot-library/src/main/kotlin/godot/core/callable/KtCallables.kt
- kt/godot-library/src/main/kotlin/godot/registration/Registration.kt
- kt/tools-common/src/main/kotlin/godot/tools/common/constants/Constraints.kt
- src/constraints.h
Some API methods couldn't be called because they exceeded the maximal amount of arguments we support.
I added a sanity check in the api generator to detect when such cases happen.
The theorical maximal number of arguments in Godot in unlimited since version 4.
The practical maximal number to date in 4.1.2 is 14 arguments.
I increased the limit to 16, to keep it a power of 2 and give us a bit of leeway.
> Increase MAX_FUNCTION_ARG_COUNT to 16.

- docs/src/doc/index.md
- docs/src/doc/user-guide/exporting.md
- docs/src/doc/user-guide/supported-platforms.md
Little fixes on doc concerning iOS support.
> fix(docs): warning formatting and gradle snippet for ios documentation

- harness/bunnymark/Benchmarker.gd
- harness/bunnymark/Benchmarker.tscn
- harness/bunnymark/README.md
- harness/bunnymark/benchmarks/BunnymarkV1DrawTexture/cs/BunnymarkV1DrawTexture.cs
- harness/bunnymark/benchmarks/BunnymarkV1DrawTexture/gd/BunnymarkV1DrawTexture.gd
- harness/bunnymark/benchmarks/BunnymarkV1Sprites/cs/BunnymarkV1Sprites.cs
- harness/bunnymark/benchmarks/BunnymarkV1Sprites/gd/BunnymarkV1Sprites.gd
- harness/bunnymark/benchmarks/BunnymarkV2/cs/BunnymarkV2.cs
- harness/bunnymark/benchmarks/BunnymarkV2/gd/BunnymarkV2.gd
- harness/bunnymark/benchmarks/BunnymarkV3/cs/Bunny.cs
- harness/bunnymark/benchmarks/BunnymarkV3/cs/BunnymarkV3.cs
- harness/bunnymark/benchmarks/BunnymarkV3/gd/Bunny.gd
- harness/bunnymark/benchmarks/BunnymarkV3/gd/BunnymarkV3.gd
- harness/bunnymark/build.gradle.kts
- harness/bunnymark/default_env.tres
- harness/bunnymark/gradle/wrapper/gradle-wrapper.properties
- harness/bunnymark/icon.png.import
- harness/bunnymark/images/banner.png.import
- harness/bunnymark/images/bunny.svg.import
- harness/bunnymark/images/godot_bunny.png.import
- harness/bunnymark/project.godot
- harness/bunnymark/settings.gradle.kts
- harness/bunnymark/src/main/kotlin/godot/benchmark/bunnymark/BunnymarkV1DrawTexture.kt
- harness/bunnymark/src/main/kotlin/godot/benchmark/bunnymark/BunnymarkV1Sprites.kt
- harness/bunnymark/src/main/kotlin/godot/benchmark/bunnymark/BunnymarkV2.kt
- harness/bunnymark/src/main/kotlin/godot/benchmark/bunnymark/BunnymarkV3.kt
- harness/bunnymark/src/main/kotlin/godot/benchmark/bunnymark/v3/Bunny.kt
- Kotlin scripts updated for Godot 4
- Gdscripts updated for Godot 4 and now typed to get the best performance out of them.
- I didn't test C#. I have never used that language and don't want to spend 4h trying to set it on my computer. If someone is willing they can do it but I don't think it's much relevant for us anyway.
- Also updated the benchmark script, so it can reach stability faster.
Kotlin JVM is incredibly faster than before, compared to GDScript (even with the extra performance from types) Our worst case is still the BunnymarkV3. That one is supposed to stress JNI calls. Despite this, we are still holding decently well.
Native images are a disappointment, I expected less performance overall because of the absence of JIT, but it seems that even BunnymarkV3 is way slower too. It …
> Update BunnyMark to Godot Kotlin 4

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
> Don't crash if any of the folders inside `ANDROID_SDK_ROOT` do not exist

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/graal/createGraalNativeImage.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/gradle/GradleSystemListener.kt
This fixes our template project by changing the expected type of `windowsDeveloperVCVarsPath` from string to a file property. This makes it more in line with our other properties with similar usages.
This also fixes the banner which is displayed when our ide plugin is not setup in the case of a gradle sync failure.
> Fix template project and ide banner showing indefinitely on gradle sync failure

- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/annotator/copy/CopyModificationAnnotator.kt
- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/project/GodotKotlinJvmProjectServiceImpl.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/messages/generalLabels.properties
Fixes #520
The performance problem should now be fixed. I can currently see no more heavy computations on my machine when using the profiler, but I encourage you to test this on your machines as well (@CedNaru, I'd be particularly grateful if you could test it on your machine, as you could reproduce the issue previously).
To test this, check out the project and run `gradlew buildPlugin`. Then from the IDE, navigate to the plugins window, click the gear icon and select `Install plugin from disk`. Then choose the zip file located under `kt/plugins/godot-intellij-plugin/build/distributions`.
The core type check threw some exceptions as i tried to apply the error to a "most relevant" parent. But in some cases this parent was "out of scope" for the error annotation and thus throwing an …
> Fix ide plugin performance issues

- docs/src/doc/getting-started/requirements.md
The following PR fixes a broken link to the exporting page in the [Requirements page](https://godot-kotl.in/en/stable/getting-started/requirements/).
> Fix broken link in `requirements.md`

- docs/src/doc/contribution/setup.md
- kt/utils/godot-build-props/build.gradle.kts
- kt/utils/godot-build-props/src/main/kotlin/godot/utils/GodotBuildProperties.kt
- kt/utils/godot-build-props/src/main/resources/build.properties
This fixes local maven publications by using the snapshot version for referenced dependencies in the gradle plugin through our build properties.
This also adds a section to our contributors documentation on how to do local publications.
> Fix local publications

- harness/tests/test/unit/test_multi_thread.gd
- src/jni/platforms/jvm_default.cpp
- src/kotlin_language.cpp
This implements `ScriptLanguage::thread_enter` and `ScriptLanguage::thread_exit` in `KotlinLanguage` to attach native threads to JVM according to their lifecycle.  
This needs https://github.com/godotengine/godot/pull/82578
> fix(cpp): implement ScriptLanguage::thread_enter and ScriptLanguage::thread_exit to attach and detach threads to JVM

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/configureThirdPartyPlugins.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/generateGdIgnoreFilesTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/setupSyncTask.kt
Previously, any attempt at applying the godot-kotlin-jvm gradle plugin to a sub project would fail with a NullPointerException becuase "ideaExtension.project" returns NULL for every gradle project except for the root project. This update addresses the issue by redirecting the task to the root project. This also means that we implicitly have to add the "idea" plugin to the root project as well.
*Edit from @chippmann :* Fixes: #546
> fix: allow godot-kotlin-jvm gradle plugin to participate in multi-module projects

- kt/build.gradle.kts
quick fix for: https://youtrack.jetbrains.com/issue/IDEA-339602/Gradle-IDEA-Ext-support-classloader-isolation
> fix: add intellij gradle plugin to root project with apply false

- .github/workflows/check-pr-engine-editor-debug-and-tests.yaml
- .github/workflows/check-pr-engine-editor-release.yaml
- .github/workflows/check-pr-engine-export-template-debug.yaml
- .github/workflows/check-pr-engine-export-template-release.yaml
- .github/workflows/check-pr-entry-generator.yaml
- .github/workflows/check-pr-godot-kotlin-symbol-processor.yaml
- .github/workflows/check-pr-jvm-godot-library.yaml
- .github/workflows/deploy-export-template.yaml
- .github/workflows/deploy-godot-editor-release.yaml
- .github/workflows/deploy-godot-entry-generator.yaml
- .github/workflows/deploy-godot-kotlin-symbol-processor.yaml
- .github/workflows/deploy-godot-library.yaml
- docs/src/doc/user-guide/versioning.md
- kt/godot-library/src/main/kotlin/godot/gen/godot/BaseMaterial3D.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/CameraAttributesPhysical.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/CanvasItem.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/NavigationLink2D.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/NavigationLink3D.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/NavigationRegion2D.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/NavigationRegion3D.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/RenderingServer.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/VideoStreamPlayer.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/Viewport.kt
- kt/godot-library/src/main/kotlin/godot/gen/godot/VisualShaderNodeTextureParameter.kt
- kt/gradle/libs.versions.toml
This updates api to godot `4.2.1`.
This bump module version to `0.8.2`.
> chore: update to godot 4.2.1 and bump module version to 0.8.2

- .github/workflows/deploy-export-template.yaml
- docs/src/doc/user-guide/versioning.md
- kt/gradle/libs.versions.toml
Export for iOS was failing because Godot was looking for the `ios` folder.
However, the current artifact was named `ios_xcode`, so the resolution for the building files was unsuccessful.
> Fix export iOS template artifact

- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/GodotKotlinSymbolProcessor.kt
This fixes a reloading bug when the user creates a custom android gradle project inside the godot editor (see #581).
This thus is a follow up bugfix of #581
Whenever a build with such a custom godot android project is executed, godot copies all assets to the android project located at `res://android` which includes our gdj files.
When our gdj tasks run, they check the project for any existing gdj files to keep track of those the user moves manually to a different location and delete stale ones. This breaks if the user has such a custom godot android gradle project as there all the gdj files are containes as well.
As a fix, we simply exclude that directory from our search (like we already do for the build directory)
> Fix gdj update in editor with custom android gradle project in godot

- src/kotlin_editor_export_plugin.cpp
- src/kotlin_editor_export_plugin.h
Implements #591
Pretty straightforward to implement.
It's not easy to check if the exported files are actually empty because Godot embeds all of them in its own file format full of meta-data and with the content encoded (even without encryption)
So I compared the size of a simple script exported by the editor before/after this commit.
Before: 767 Bytes
After: 241 Bytes
I think it's safe to say that it's working.
> Source files are now exported without the code.

- harness/tests/src/main/kotlin/godot/tests/Invocation.kt
- kt/godot-library/src/main/kotlin/godot/core/bridge/Dictionary.kt
- kt/godot-library/src/main/kotlin/godot/core/bridge/VariantArray.kt
- kt/godot-library/src/main/kotlin/godot/core/math/Basis.kt
- kt/godot-library/src/main/kotlin/godot/core/math/Quaternion.kt
- kt/godot-library/src/main/kotlin/godot/core/math/Vector2.kt
- kt/godot-library/src/main/kotlin/godot/core/math/Vector3.kt
- kt/godot-library/src/test/kotlin/godot/core/Vector2Test.kt
- kt/godot-library/src/test/kotlin/godot/core/Vector3Test.kt
Implement #505 
Also sneaking in a small change I wanted for VariantArray and Dictionary. It doesn't change anything for calling code, but it removes the part that complains about a function using the same name as a constructor.
I could have implemented #590 too, but I want to avoid touching bridges in the master with the GDKotlin rework branch around
> Add new core methods

- kt/entry-generation/godot-kotlin-symbol-processor/src/main/kotlin/godot/annotation/processor/ext/ksDeclarationExt.kt
This improves error handling if code of the user does not compile.
Before we only handled compilation errors at class level but with this we nod also handle errors on members we care about.
> Improve ksp error handling upon compilation issues

- kt/godot-library/src/main/kotlin/godot/core/Variant.kt
Quick change to how vararg arguments are sent to the buffer. Now we use the VariantMapper instead of testing a thousand classes in a giant when statement.
This is not a new approach, we already use the same logic when creating a VariantArray and Dictionary to check if the type is compatible with Godot.
> Kotlin to Godot vararg optimization

- src/script/jvm_placeholder_instance.cpp
- src/script/jvm_placeholder_instance.h
- src/script/jvm_script.cpp
When the project is not build, or at least not rebuilt after adding new scripts or checking out your project, it's easy to use invalid scripts. This PR adds a warning to nodes with invalid jvm scripts.
> Add warning for invalid jvm scripts

- src/language/gdj_language.cpp
- src/type_manager.cpp
- src/type_manager.h
Scripts exports weren't properly (re)loaded and caused properties to not be set in the inspector when a node was selected.
> Fix inspector exports

- kt/godot-library/src/main/kotlin/godot/extensions/PackedSceneExt.kt
Little fix; when we migrated to godot 4, we forgot to rename this extension function
> Fix extension method name

- src/kotlin_editor_export_plugin.cpp
- src/kt_variant.h
This simplify cpp read and write buffer protocol for core types.  
This reinterprets byte buffer to core type to avoid multiple calls to get each primitives.  
This needs test on all platforms to be sure we don't have memory layout troubles, even if we shouldn't as all core types are perfectly aligned.
> enh: Simplify cpp core type buffer protocol read and write

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/createMainDexFileTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageBootstrapDexJarTask.kt
- kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/android/main-dex-rules.proguard
- src/gd_kotlin.cpp
- src/lifecycle/class_loader.cpp
This implements multidex support for both usercode jar and bootstrap jar:
This also fixes an issue regarding dynamic code loading on android 14 when built with the corresponding target sdk version: https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading
Android export tested on our tests project.
Will test the 3D demo project tomorrow as well
> Support multidex and fix export for android 14 devices

- src/jvm_wrapper/bridge/variant_array_bridge.cpp
- src/jvm_wrapper/memory/transfer_context.cpp
- src/jvm_wrapper/registration/kt_class.cpp
- src/language/gdj_language.cpp
- src/language/gdj_language.h
- src/resource_format/jvm_resource_format_loader.cpp
- src/script/jvm_script.cpp
- src/script/jvm_script.h
- src/script/jvm_script_manager.cpp
- src/script/jvm_script_manager.h
We never properly cached the Kotlin and Java Scripts.
Each time you reload the .jar, new ones are created instead of updating the ones already here which triggers a nasty side effect.
The original Script is replaced inside the ResourceLoader by the new one. And its path taken as well.
The consequence is that if you got a Godot scene opened when reloading and then save, the script is no longer recognized as an external resource (because no path) and is stored as an internal script (which we don't support).
I also move the content of update_export to another method. The reason is that Godot calls that method whenever it detects a change in the source files, which is totally useless in our case because only the .jar matters.
This doesn't require testing on each OS, but I welcome if you can …
> Fix PathScript caching.

- harness/tests/src/main/kotlin/godot/tests/exception/ExceptionTest.kt
- harness/tests/test/unit/test_exception.gd
- src/jni/env.cpp
- src/jni/env.h
This improves the jni error reporting inside the godot editor by grabbing the stacktrace from the jvm and printing them using the godot print commands. Only applies to tool mode. In all other cases, we still print the error using the jni provided method which just prints to the console.
> Add better jni error reporting inside the godot editor

- kt/godot-library/src/main/kotlin/godot/global/GDMath.kt
The moveToward function in GDMath class under godot.global package has wrong behavior when it goes from 0 to negative value.
I query realized the Godot source code,as follows.
`static _ALWAYS_INLINE_ float move_toward(float p_from, float p_to, float p_delta) { return abs(p_to - p_from) <= p_delta ? p_to : p_from + SIGN(p_to - p_from) * p_delta; }`
The implementation in Kotlin should be as follows.
`fun moveToward(from: Float, to: Float, delta: Float) = if (abs(to - from) <= delta) to else from + (to - from).sign * delta`
> fix function moveToward

- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/extension/psiClass.kt
This extension wasn't used anymore and was causing troubles in intellij plugin verification.
> fix(intellij-plugins): remove unused declaration extensions in psiClass.kt

- docs/src/doc/contribution/setup.md
Expanded the instructions in the setup.md contribution guide. The update includes more detailed information for checking Java installation, clarifies branch tagging for Godot cloning, and provides better guidance for building the engine and samples.
> Update setup documentation in contribution guide

- src/jni/env.cpp
This fixes the spawning of jni warning logs when grabbing the stacktrace from the jvm.
When implementing it initially, i did not notice the spam of errors as i checked one exception. But if there are more than one (let's say in a progress call) then the console is spammed with jni warnings for not checked exceptions.
> Fix exception describe

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/packageBootstrapJarTask.kt
If the users project defines a version in gradle, the fat jar automatically inherits that.
If that is the case, our export plugin can no longer find the jar.
This fixes that by forcefully removing any version set for the fat jar artifact name.
> Fix fat jar creation if users project defines a version

- docs/mkdocs.yml
- docs/src/doc/contribution/test-change-from-branch.md
This adds documentation on how to build this module from a specific branch and how to test that in a Godot Kotlin/JVM project
> Add documentation on how to use the project state from a specific branch

- src/script/jvm_script_manager.cpp
- src/script/jvm_script_manager.h
Solves a bug when scripts are (re)loaded in the editor.
Cherry-pick from the cpp reloading branch for the 4.3 release.
> Improve script cache

- kt/godot-library/src/main/kotlin/godot/global/GDMath.kt
- kt/godot-library/src/main/kotlin/godot/global/GDPrint.kt
- kt/godot-library/src/main/kotlin/godot/global/GDRandom.kt
- kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/godot-kotlin-graal-jni-config.json
- src/jvm_wrapper/bridge/gd_print_bridge.cpp
- src/jvm_wrapper/bridge/gd_print_bridge.h
Resolves #590 and #543
I decided to remove the alternative Long/Double version of the random methods to remove confusion. Those helpers parameters were internally downsized and the return value were never able to use the extended size of the type. 
Some of the results were actually inacurate because casting a Long to an Int when it's bigger than its maximal value can result in a negative number.
> Add/Fix missing GD singleton methods.

- src/jvm_wrapper/registration/kt_property.cpp
- src/jvm_wrapper/registration/kt_property.h
- src/script/jvm_instance.cpp
- src/script/jvm_script.cpp
C++ counterpart to the lateinit change #668. The editor won't try to get the default value for Object anymore.
Object is the only allowed lateinit, but Godot doesn't handle default values for that type anyway.
Here a simple proof using GDScript, a property is declared with a default value, but the inspector can't see it:
> Don't fetch default value for Object properties

- .github/workflows/test_linux.yml
- .github/workflows/test_macos.yml
- .github/workflows/test_windows.yml
- docs/src/doc/contribution/setup.md
- docs/src/doc/user-guide/debugging.md
- docs/src/doc/user-guide/exporting.md
- harness/tests/.gitignore
- harness/tests/export_presets.cfg
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/generateGdIgnoreFilesTask.kt
- src/gd_kotlin.cpp
- src/kotlin_editor_export_plugin.cpp
- src/lifecycle/paths.h
- src/logging.h
This makes the jre folder platform dependent.
This makes it possible for a project to have multiple jre folder simultaneously on the file system. The module then automatically picks the correct one for the current platform.
The main advantage of this is that on a project with multiple people working on it, the embedded jre can be committed to the repository for each platform together with the built jar and a project member does not need to have java locally installed and JAVA_HOME set. Which is especially useful if one is working with non programmers.
**Note:** Breaking change. Needs special notes in release notes!
> Make jre folder platform dependent

- kt/godot-library/src/main/kotlin/godot/core/memory/MemoryManager.kt
- kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/godot-kotlin-graal-jni-config.json
- src/binding/kotlin_binding_manager.cpp
- src/binding/kotlin_binding_manager.h
- src/jvm_wrapper/memory/memory_manager.cpp
- src/jvm_wrapper/memory/memory_manager.h
The issue was caused by some Godot objects with a Kotlin binding being destroyed later than the module. Our binding callbacks needs to access one of the singleton of our module, which was already destroyed at this point.
I just slightly changed the cleanup operation to also include Object and not just decrement RefCounted.
> Fix closing of module

- src/script/jvm_script.cpp
Resources should still gather default values.
For node types (which are treated as node paths in the inspector) we return an empty variant so we can set them.
@CedNaru please look at this carefully. I'm very unsure if this is the proper way of dealing with this, but it works
> Fix default value retrieval for resources and node paths

- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/NodeTypeHintStringGenerator.kt
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/generator/hintstring/ResourceHintStringGenerator.kt
Resolves https://github.com/utopia-rise/godot-kotlin-jvm/issues/658
This fixes the generated type hint for custom classes extending resource types and node types.
With normal registration this did not cause any issues but with fqdn registration it did as not the fqdn name was used as a hint string but the simple name.
**Important:** this does NOT solve the same issue for libraries! If a library registeres a custom resource with fqdn registration enabled but the users project uses normal registration, it uses normal registration. The users project config always overrides the config of any library used. This issue is not as easy solveable atm and i first need to think of a proper solution. This PR fixes the issue at hand though. I created a follow up issue here: #677
> Fix custom classes hint string

- kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/godot-kotlin-graal-jni-config.json
This fixes GDPrint$Bridge::getStacktrace jni signature for graalvm native-image.
> fix(graal): set right signature for GDPrint$Bridge::getStacktrace in graal jni config

- .github/workflows/trigger_on_push_master.yml
This uploads final binaries as release artifact's on master builds
This has the benefit that each master build can be properly tested.
PR builds alone are not always enough if you have two PR's merged none of the builds in these PR's have the changes from the other PR. only master builds contain every change.
This also allows for safer and easier testing before releases which does not rely that much on local build's and build setups and we test actual binaries we would ship.
> Create and upload final binaries on master builds

- harness/tests/src/main/java/godot/tests/JavaTestClass.java
- kt/godot-library/src/main/kotlin/godot/core/KtObject.kt
- kt/godot-library/src/main/kotlin/godot/core/bridge/Dictionary.kt
- kt/godot-library/src/main/kotlin/godot/core/bridge/VariantArray.kt
I just discovered from a Discord conversation that it was not possible to create a new VariantArray and Dictionary from Java.
They both require a KClass which is a Kotlin STD object and the fake constructor we use for it is inlined when the actual one is internal. Inline functions are not visible from Java.
I created a new public constructor that directly take Java classes as arguments. Boilerplate to use, but we have no choice.
> Make VariantArray and Dictionary constructors visible to Java

- harness/tests/build.gradle.kts
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt
This aligns the naming of the coroutine flag to the ones we already have and to what gradle and kotlin are doing in their plugins
> Fix coroutines gradle flag name

- harness/tests/scripts/godot/tests/Invocation.gdj
- harness/tests/scripts/godot/tests/coroutine/CoroutineTest.gdj
- harness/tests/scripts/godot/tests/signal/SignalTest.gdj
- harness/tests/src/main/kotlin/godot/tests/coroutine/CoroutineTest.kt
- harness/tests/test/unit/test_coroutines.gd
- kt/godot-coroutine-library/src/main/kotlin/godot/coroutines/awaitDeferred.kt
- kt/godot-coroutine-library/src/main/kotlin/godot/coroutines/awaitResourceLoad.kt
This adds the following coroutine utility functions:
- awaitDeferred -> like callDeferred but for cotoutines. helpful to run stuff on the main thread from a coroutine
- awaitLoad -> load resources with progress from coroutines
> Add some coroutines utility functions

- .github/workflows/deploy_jvm.yml
- kt/plugins/godot-intellij-plugin/build.gradle.kts
This fixes the verification error in the idea plugin. An empty string now basically means the same as `999.*` previously.
This also fixes the jvm publications as by accident after every publish, we tried to publish everything a second time.
I tested this locally with mavenLocal and it worked but definitely needs to be tested from the maven snapshot repo before moving that to the prod repo @piiertho
> Fix jvm publications

- src/jvm_wrapper/memory/transfer_context.cpp
- src/jvm_wrapper/memory/transfer_context.h
- src/kt_variant.h
I noticed that we never added the new PackedVector4Array to the Variant.h.
So I just took the opportunity to rework the file a bit.
The function bodies are almost unchanged, only the general structure of the file changed. Instead of the KtVariant namespace, I have put all methods into the new `BufferToVariant ` and `VariantToBuffer` structures. Because everything is static, the structures act like a more fine-grained namespace. This is also how Godot does it through its codebase.
Note that I also removed the initializer function for the array of function pointers. It's now done statically, no "if" is required during runtime anymore.
Before :
```cpp
static void init_to_kt_methods(void (*to_kt_array[Variant::Type::VARIANT_MAX])(SharedBuffer*, const Variant&)) {
// Long initializer...
} …
```
> Rework Variant.h

- .github/workflows/assemble_export_templates.yml
- .github/workflows/assemble_ios.yml
- .github/workflows/assemble_linux.yml
- .github/workflows/assemble_macos.yml
- .github/workflows/assemble_windows.yml
- .github/workflows/build_android.yml
- .github/workflows/deploy_docs.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_linux_exports.yml
- .github/workflows/test_macos.yml
- .github/workflows/test_macos_exports.yml
- .github/workflows/test_windows.yml
- .github/workflows/test_windows_exports.yml
- .github/workflows/trigger_dev.yml
- .github/workflows/trigger_on_pull_request.yml
- .github/workflows/trigger_on_push_master.yml
- .github/workflows/trigger_on_tag.yml
- config.py
- docs/src/doc/user-guide/exporting.md
- kt/gradle/libs.versions.toml
- src/version.h
- versionBumpGuide.txt
Currently, the editor is not able to automatically use our templates because there is a mismatch between its name and the name of the template. We have so far build our custom editor using the same "name" as the official godot, which creates a conflict.
I made the changes so that the next release is going to use the name `4.3.stable.jvm.0.11.0`.
We can't change the prefix `4.3-stable` unless we directly Godot files, but we can append anything we want to it, so I picked `jvm.ourcurrentversion`
Without that change, users can't properly export without manually setting a release and a debug export template in their export preset.
This issue didn't happened before because we were using the same name as the official template for ours. I changed last before the last release so people could have …
> Fix template usage

- kt/api-generator/src/main/kotlin/godot/codegen/constants/JvmReservedMethods.kt
- kt/api-generator/src/main/kotlin/godot/codegen/generationEntry.kt
- kt/api-generator/src/main/kotlin/godot/codegen/models/enriched/EnrichedClass.kt
- kt/api-generator/src/main/kotlin/godot/codegen/models/enriched/EnrichedMethod.kt
- kt/api-generator/src/main/kotlin/godot/codegen/services/IClassService.kt
- kt/api-generator/src/main/kotlin/godot/codegen/services/impl/ClassService.kt
The code generation (and not the compile time) was more than 2 minutes on my computer. 
After profiling the generator, I found the culprit to be a single method responsible for 92% of the computation time.
ClassService::getClasses() was called in many places in the code, always computing the same expensive operation.
Simply caching the result into a variable completly erase the computation time.
With that change, the code generation takes now less than 3s.
I also took the opportunity to unify the search for the methods used by properties. It was previously done in 2 steps that I merged together.
> Faster API Generation

- harness/tests/scripts/godot/tests/coroutine/CoroutineTest.gdj
- harness/tests/src/main/kotlin/godot/tests/coroutine/CoroutineTest.kt
- harness/tests/test/unit/test_coroutines.gd
- kt/godot-coroutine-library/src/main/kotlin/godot/coroutines/AwaitFrames.kt
- kt/godot-coroutine-library/src/main/kotlin/godot/coroutines/GodotCoroutine.kt
- kt/godot-coroutine-library/src/main/kotlin/godot/coroutines/GodotDispatchers.kt
- kt/godot-coroutine-library/src/main/kotlin/godot/coroutines/awaitMainThread.kt
This adds coroutines dispatchers for godot's main thread and thread pool.  
EDIT: This also adds method to run code block on physics and process frames.
> feat(coroutines): implement main thread and thread pool dispatchers

- src/editor/godot_kotlin_jvm_editor.cpp
Minor fix for the JVM project generation.
I realized that after generating the project, the files weren't appearing in the Godot editor.
The reason is that Godot only refresh its filesystem automatically when you unfocus the editor and focus it again.
The assumption is that the user left the Godot window to use some external tools that can potentially change files in the project. But for any changes made by Godot itself, you have to manually call the scanner. The reason is so the editor doesn't constantly check the file system for changes but only do it on demand.
> Scan after generating project

- harness/tests/scripts/godot/tests/coroutine/CoroutineTest.gdj
- harness/tests/src/main/kotlin/godot/tests/coroutine/CoroutineTest.kt
- harness/tests/test/unit/test_coroutines.gd
- install_vulkan_sdk_macos.sh
- kt/api-generator/src/main/kotlin/godot/codegen/services/impl/AwaitGenerationService.kt
- kt/api-generator/src/main/kotlin/godot/codegen/services/impl/LambdaCallableGenerationService.kt
- kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/Callables.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/LambdaCallable.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/NativeCallable.kt
- kt/godot-library/godot-coroutine-library/src/main/kotlin/gen/godot/coroutines/Await.kt
- kt/godot-library/godot-coroutine-library/src/main/kotlin/godot/coroutines/GodotDispatchers.kt
- kt/plugins/godot-gradle-plugin/src/main/resources/godot/gradle/godot-kotlin-graal-jni-config.json
- src/jvm_wrapper/bridge/callable_bridge.cpp
- src/jvm_wrapper/bridge/callable_bridge.h
- src/jvm_wrapper/bridge/lambda_callable_bridge.cpp
- src/jvm_wrapper/bridge/lambda_callable_bridge.h
- src/jvm_wrapper/kotlin_callable_custom.cpp
- src/jvm_wrapper/kotlin_callable_custom.h
This adds a `onCancel` callback on `LambdaCallable` to cancel coroutine when a callable used within is canceled.
> feat(coroutine): Add LambdaCallable::onCancel to cancel coroutine when callable is cancelled

- kt/godot-library/godot-core-library/build.gradle.kts
- kt/godot-library/godot-core-library/src/main/kotlin/godot/runtime/Bootstrap.kt
- src/gd_kotlin.cpp
- src/gd_kotlin.h
- src/jvm_wrapper/bootstrap.cpp
- src/jvm_wrapper/bootstrap.h
- src/lifecycle/jvm_manager.cpp
Resolve #757
The module will now refuse to fully boot and print an error if there is a mismatch between the version of the module and the version of the bootstrap.
Took the opportunity to change where bootstrap is loaded so it happens before any other risk of JNI signature mismatch due to difference in version.
> Check module and jar have the same version

- docs/src/doc/contribution/setup.md
- docs/src/doc/getting-started/requirements.md
This adds a bit of warning documentation on the problems encountered while using microsofts jdk builds on windows when trying to build our project
The issue is outlined [here](https://github.com/microsoft/openjdk/issues/339) and also applicable to us.
Even if specifying a jvm vendor manually using jvmToolchain, the task `instrumentCode` from the intellij plugin sdk does not adhere to that constraint.
So there is nothing else we can do on our side to fix this issue.
> Add documentation on known issue with microsofts jdk on windows

- kt/godot-library/godot-core-library/src/main/kotlin/godot/runtime/Bootstrap.kt
We had several reports of people having weird behavior with their scripts.
The cause was the existence of a companion object storing or using a reference to a Godot object.
A bit tricky to explain but basically the very first time an instance of a script was used, the class itself was initialized and so its static blocks. 
When an instance is created from Godot directly (via a scene for example), the native object already existe and we pass its pointer directly to the new script instance. This static class init had the side effect to pass this pointer to the Godot object created in the companion object instead of the script. 
The end result was an static object with the wrong pointer set and the script create a completely separate native object...
To fix this, I ensure that all those …
> Force early initialization for scripts classes

- .github/workflows/deploy_jvm.yml
This fixes the ide plugin deployment.
Historically we had a build matrix for the ide plugin when we were targeting ide versions explicitly.
In #758 i forgot to update that matrix as is did not remember that we did it like this.
This build matrix is obsolete as we only have a single ide plugin version nowadays. Hence i removed it completely and let the gradle setup take care of the used idea sdk like we have for the regular ide verify build check for pull request workflows.
Now the deployment also uses the idea sdk version defined in `libs.versions.toml`
> Fix ide plugin deployment and remove obsolete ide plugin specific matrix

- src/language/jvm_language.cpp
- src/language/jvm_language.h
Yes, this is what Godot 4.4 actually requires now to be able to reload scripts.
> Fix script reloading

- src/language/gdj_language.cpp
I didn't expect that those pointers could be null...
There are some cases when Godot does that in the editor, instantly causing a crash. (Like trying to extend a script through the UI)
> Handle null pointers in get_global_class_name

- src/jvm_wrapper/bridge/callable_bridge.cpp
- src/jvm_wrapper/bridge/dictionary_bridge.cpp
- src/jvm_wrapper/bridge/node_path_bridge.cpp
- src/jvm_wrapper/bridge/packed_array_bridge.h
- src/jvm_wrapper/bridge/packed_byte_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_float_32_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_float_64_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_int_32_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_int_64_array_bridge.cpp
- src/jvm_wrapper/bridge/string_name_bridge.cpp
- src/jvm_wrapper/bridge/variant_array_bridge.cpp
- src/jvm_wrapper/memory/memory_manager.cpp
- src/kt_variant.h
- src/variant_allocator.h
We profiled a long time ago that the constant use of memnew in kt_variant.h was a potential bottleneck in situation where a lot of data were exchange between Godot and the JVM. It wasn't high priority, but 2 years past, and we still didn't take the time to adress it.
I created our own little VariantAllocator, taking heavy inspiration of what Godot itself does in its implementation of Variant.
https://github.com/godotengine/godot/blob/2303ce843a362cf5497ca3336451de23793eb711/core/variant/variant.h#L164
> Use PagedAllocator for native core types

- harness/tests/src/main/kotlin/godot/tests/packedarray/PackedArrayTest.kt
- harness/tests/test/unit/test_packed_arrays.gd
- kt/entry-generation/godot-entry-generator/src/main/kotlin/godot/entrygenerator/ext/TypeExtensions.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/packed/PackedVector2Array.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/packed/PackedVector3Array.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/packed/PackedVector4Array.kt
- kt/tools-common/src/main/kotlin/godot/tools/common/constants/Classes.kt
- src/jvm_wrapper/bridge/packed_vector2_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_vector2_array_bridge.h
- src/jvm_wrapper/bridge/packed_vector3_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_vector3_array_bridge.h
- src/jvm_wrapper/bridge/packed_vector4_array_bridge.cpp
- src/jvm_wrapper/bridge/packed_vector4_array_bridge.h
Like we did with the byte/int/float versions of PackedArrays, I added another batch conversion for Vector PackedArray.
It's the same pattern as before, except there is an extra conversion step to/from a FloatArray (because obviously the JVM doesn't have any native Vector2 arrays).
For example, we pass a Vector2 has a pair of floats, so an array of Vector2 is converted into an array of floats with double the size.
> Add batched conversion to PackedVector arrays

- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/KtObject.kt
- src/script/jvm_instance.cpp
Solve #744
It was technically possible to make those methods works, but they are special cases (like notification() and are not part of the regular Godot API so they are not generated alongside Object.kt.
I add them as unimplemented methods in KtObject and fixed toString in the Script instance.
> Add missing core Object methods.

- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/Variant.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/Dictionary.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/bridge/VariantArray.kt
- src/kt_variant.h
Partially solve #705
Sadly it doesn't work if the generic type use a VariantCaster like Int.
Any Variant<Int> is seen as having a Variant.LONG by the C++ side (because Variant.INT doesn't exist, everything is 64bits in a variant). It means that if you export a Variant<Int> and set it in the inspector, it won't work because we can only type it to Long and not Int causing a cast exception at runtime.
We will need a more refined solution for everything that is register by the users (method, properties, and callables)
> Add typing to JVM containers from buffer.

- src/jni/types.cpp
- src/jni/types.h
- src/lifecycle/class_loader.cpp
So far we have always created a ClassLoader with a parent set to null. It was the right way to make one that default to the system classloader, back in Java 8...
Since then, they added the new module system and classLoaders without parent don't have access to any other module than the base one, any additional one would result in a ClassNotFound error for people trying to use java sql for example.
Related issue:
https://bugs.openjdk.org/browse/JDK-8161269
I confirmed with a user who couldn't use the java sql module that the change fixed their issue.
> Use the correct parent for ClassLoader

- .github/workflows/assemble_android.yml
- .github/workflows/assemble_export_templates.yml
- .github/workflows/assemble_ios.yml
- .github/workflows/assemble_linux.yml
- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_jvm.yml
- .github/workflows/build_linux.yml
- .github/workflows/deploy_create_draft_release.yml
- .github/workflows/deploy_jvm.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_linux_exports.yml
- .github/workflows/test_macos.yml
- .github/workflows/test_macos_exports.yml
- .github/workflows/test_windows.yml
- .github/workflows/test_windows_exports.yml
- .github/workflows/trigger_dev.yml
- .github/workflows/trigger_on_pull_request.yml
- .github/workflows/trigger_on_push_master.yml
- .github/workflows/trigger_on_tag.yml
This runs the android builds in parallel and adds some minor improvements to the CI/CD pipeline, like only defining a fixed linux version where necessary.
**Note:** I would only merge this after the next release is done in case there is an issue i did not see
>  Run android builds in parallel and minor improvements

- .github/workflows/assemble_linux.yml
- .github/workflows/assemble_macos.yml
- .github/workflows/assemble_windows.yml
- .github/workflows/build_jvm.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_linux_exports.yml
- .github/workflows/test_macos.yml
- .github/workflows/test_macos_exports.yml
- .github/workflows/test_windows.yml
- .github/workflows/test_windows_exports.yml
- kt/build.gradle.kts
- kt/godot-library/build.gradle.kts
- kt/godot-library/godot-core-library/build.gradle.kts
- kt/godot-library/godot-coroutine-library/build.gradle.kts
- kt/godot-library/godot-extension-library/build.gradle.kts
- src/editor/godot_kotlin_jvm_editor.cpp
- src/gd_kotlin.cpp
- src/lifecycle/paths.h
We worked on removing dependency of the editor on the `bootstrap.jar` little by little over the months.
It's time to say goodbye to it.
From now on, only a single bootstrap will be generated at the same time as the main.jar
> Remove editor bootstrap

- kt/plugins/godot-intellij-plugin/src/main/kotlin/godot/intellij/plugin/module/GodotModuleBuilder.kt
- kt/plugins/godot-intellij-plugin/src/main/resources/template/project.godot.intellij_template
Fix #802
Version can only be x.y in this file, (like 4.2, 4.3, 4.4..., they never include the patch version in it).
> Make project.godot template version dynamic.

- src/jni/env.cpp
- src/kt_variant.h
FIx #808 
Little mistake we made when parsing a String from JNI instead of the bytebuffer. 
We were using Godot's String regular constructor that takes a char array, but that constructor assumes it's latin encoding and not utf8. 
We never noticed because we use the bytebuffer in most places, but non-ascii characters were breaking when printing to Godot for example.
> Parse JNI Strings as utf8

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/setupTasks.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/createBootstrapDexJarTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageBootstrapDexJarTask.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageMainDexJarTask.kt
Resolves #811 and resolves #813
This resolves a crash when running an exported android project.
The resulting godot-bootstrap-dex.jar does not contain any resource files, only class files as the r8 tool only handles class files.
I for now created a new task which modifies the jar after creation to add missing and required resources to it.
However: I'm not sure if there is not a better approach. This approach works, but is not ideal IMO. AFAIK there is no way to tell r8 to handle the resource copy for us. And I'm not aware of a gradle task which can handle this for us automatically.
Note: this resource copy problem only applies to the bootstrap dex jar. For the main dex jar, we already handled missing resources manually. See here: …
> GH-811 GH-813 Copy missing resource files for android exports

- docs/src/doc/user-guide/exporting.md
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/projectExt/setupTasks.kt
- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/GenerateEmbeddedJreTask.kt
Resolves https://github.com/utopia-rise/godot-kotlin-jvm/issues/163
> Add GenerateEmbeddedJreTask to generate JRE

- src/kotlin_editor_export_plugin.cpp
- src/kotlin_editor_export_plugin.h
- src/lifecycle/paths.h
Resolves #801 
This explicitly excludes our jvm dir by default. The jars we need we add manually in the export plugin, and this takes predecence over what we exclude here. So these files are still present.
Before this change, these jar files were added twice, breaking the android export.
@CedNaru This change kinda prevents your idea of loading jars dynamically with the jar resource loader.
We can either worry about this once we implement multi jars or we can instead, not explicitly add the bootstrap jar and the main jar in the export plugin anymore and instead let it happen atomatically through the resource loader.
Because of this decision; this is still a draft
> GH-801 Exclude jvm dir from export

- src/editor/build/build_manager.cpp
- src/editor/build/build_manager.h
- src/editor/build/gradle_task_runner.cpp
- src/editor/build/gradle_task_runner.h
- src/editor/dialog/build_dialog.cpp
- src/editor/dialog/build_dialog.h
- src/editor/godot_kotlin_jvm_editor.cpp
- src/editor/godot_kotlin_jvm_editor.h
- src/gd_kotlin.cpp
The build task was only displaying something when the entire task was done running.
I added streaming to it so you can see what is happening in case the task takes a while. On top of that, I added a small animation to show that there is activity.
You also have now a selector to pick which task you want to run.
So far, only 3 options are present:
- Regular build (debug by default)
- Release build
- Generate Embedded JRE.
I also fixed a small bug, the editor was still complaining about the lack of bootstrap (if the project hasn't been built once yet).
It was an error I made in the PR removing the editor bootstrap, I only wanted to display an error if the game itself was launched without bootstrap, but I used the project manager hint instead of the editor hint. …
> Improve Gradle Task Runner

- kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageMainDexJarTask.kt
This fixes an issue introduced with #814
As we now copy all resources, we created duplicate entries for the registration service file, which caused issues on android exports where the jar could not be loaded because of duplicate jar entries (the service file)
> Remove explicit registration entry copy as it creates a duplicate entry

- harness/tests/src/main/kotlin/godot/tests/callable/CallableMethodBindTest.kt
- harness/tests/test/unit/test_callable_method_bind.gd
- kt/api-generator/src/main/kotlin/godot/codegen/services/impl/CallableGenerationService.kt
- kt/api-generator/src/main/kotlin/godot/codegen/services/impl/SignalGenerationService.kt
- kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/Callables.kt
- kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/LambdaCallables.kt
- kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/MethodCallables.kt
- kt/godot-library/godot-core-library/src/main/kotlin/gen/godot/core/Signals.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/Variant.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/callback/LambdaCallable.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/callback/MethodCallable.kt
- kt/godot-library/godot-core-library/src/main/kotlin/godot/core/callback/Signal.kt
- kt/tools-common/src/main/kotlin/godot/tools/common/constants/Classes.kt
Depends on #803 
Add numbered typed MethodCallableX classes, which now shared a common CallableX interface with LambdaCallableX.
SIgnalX also now use this interface for typ safe connection instead of only `unsafeConnect`
> Add CallableX and MethodCallableX classes

- .github/actions/mac-host-patches/action.yml
- .github/workflows/build_macos.yml
This creates a dedicated github action to patch the macos host everytime we need it (like currently for moltenvk).
The idea is, that we keep this action and just have to make edits to it when we need to patch macos in the future again instead of searching in our action files for the correct location.
Currently this is needed for moltenvk, as moltenvk now requires xcode 16 which is not the default on `macos-latest` as that still used macos 14 instead of 15: https://github.com/actions/runner-images?tab=readme-ov-file#available-images)
> Add build action to patch macos engine build host

- generate_templates.py
When working on the Gradle template, I found that running generate_templates.py changed the order of the files in templates.h, not just their contents. There's apparently no guaranteed order for `os.walk`, so the diff was messy: 
This cleans that up by iterating in a stable order, taken from [this stackoverflow answer](https://stackoverflow.com/a/18282401).
Clean diff now!
> Use stable file ordering when generating templates
